package org.xtext.example.generator;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.xtext.example.cv.Education;
import org.xtext.example.cv.Experience;
import org.xtext.example.cv.Model;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class CvGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EList<EObject> _contents = resource.getContents();
    for (final EObject obj : _contents) {
      if ((obj instanceof Model)) {
        final Model cv = ((Model) obj);
        this.generateHTML(cv, fsa);
      }
    }
  }

  public void generateHTML(final Model cv, final IFileSystemAccess2 fsa) {
    String _name = cv.getName();
    String _plus = (_name + ".html");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<meta charset=\"UTF-8\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<title>");
    String _title = cv.getTitle();
    String _plus_1 = (_builder.toString() + _title);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("</title>");
    _builder_1.newLine();
    _builder_1.append("                ");
    _builder_1.append("<style>");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("body {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("font-family: \'Arial\', sans-serif;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("line-height: 1.6;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("margin: 0;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("padding: 0;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("background-color: #f4f4f4;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("color: #333;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("header {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("background-color: #333;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("color: #fff;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("text-align: center;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("padding: 2em 0;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("h1, h2 {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("color: #333;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("section {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("max-width: 800px;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("margin: 20px auto;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("background-color: #fff;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("padding: 20px;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("border-radius: 8px;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("h2 {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("border-bottom: 2px solid #333;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("padding-bottom: 10px;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("margin-bottom: 20px;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("p {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("margin-bottom: 15px;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("font-size: 16px;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("color: #555;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("ul {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("list-style-type: none;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("padding: 0;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("ul li {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("margin-bottom: 10px;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append(".education, .experience {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("margin-bottom: 30px;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("footer {");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("text-align: center;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("padding: 1em 0;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("background-color: #333;");
    _builder_1.newLine();
    _builder_1.append("                        ");
    _builder_1.append("color: #fff;");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("                ");
    _builder_1.append("</style>");
    _builder_1.newLine();
    _builder_1.append("            ");
    _builder_1.append("</head>");
    _builder_1.newLine();
    _builder_1.append("            ");
    _builder_1.append("<body>");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("                ");
    _builder_1.append("<header>");
    _builder_1.newLine();
    _builder_1.append("                    ");
    _builder_1.append("<h1>");
    String _plus_2 = (_plus_1 + _builder_1);
    String _name_1 = cv.getName();
    String _plus_3 = (_plus_2 + _name_1);
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append("</h1>");
    _builder_2.newLine();
    _builder_2.append("                    ");
    _builder_2.append("<p>");
    String _plus_4 = (_plus_3 + _builder_2);
    String _title_1 = cv.getTitle();
    String _plus_5 = (_plus_4 + _title_1);
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append("</p>");
    _builder_3.newLine();
    _builder_3.append("                ");
    _builder_3.append("</header>");
    _builder_3.newLine();
    _builder_3.newLine();
    _builder_3.append("                ");
    _builder_3.append("<section>");
    _builder_3.newLine();
    _builder_3.append("                    ");
    _builder_3.append("<h2>À propos de moi</h2>");
    _builder_3.newLine();
    _builder_3.append("                    ");
    _builder_3.append("<p>");
    String _plus_6 = (_plus_5 + _builder_3);
    String _about = cv.getAbout();
    String _plus_7 = (_plus_6 + _about);
    StringConcatenation _builder_4 = new StringConcatenation();
    _builder_4.append("</p>");
    _builder_4.newLine();
    _builder_4.append("                ");
    _builder_4.append("</section>");
    _builder_4.newLine();
    _builder_4.newLine();
    _builder_4.append("                ");
    _builder_4.append("<section class=\"education\">");
    _builder_4.newLine();
    _builder_4.append("                    ");
    _builder_4.append("<h2>Éducation</h2>");
    _builder_4.newLine();
    _builder_4.append("                    ");
    _builder_4.append("<ul>");
    _builder_4.newLine();
    _builder_4.append("                        ");
    _builder_4.newLine();
    {
      EList<Education> _education = cv.getEducation();
      for(final Education education : _education) {
        _builder_4.append("                       ");
        _builder_4.append("<li>");
        String _degree = education.getDegree();
        _builder_4.append(_degree, "                       ");
        _builder_4.append(" - ");
        String _university = education.getUniversity();
        _builder_4.append(_university, "                       ");
        _builder_4.append(" (\'");
        int _year = education.getYear();
        _builder_4.append(_year, "                       ");
        _builder_4.append("\')</li>");
        _builder_4.newLineIfNotEmpty();
      }
    }
    _builder_4.append("                    ");
    _builder_4.append("</ul>");
    _builder_4.newLine();
    _builder_4.append("                ");
    _builder_4.append("</section>");
    _builder_4.newLine();
    _builder_4.newLine();
    _builder_4.append("                ");
    _builder_4.append("<section class=\"experience\">");
    _builder_4.newLine();
    _builder_4.append("                    ");
    _builder_4.append("<h2>Expérience professionnelle</h2>");
    _builder_4.newLine();
    _builder_4.append("                    ");
    _builder_4.append("<ul>");
    _builder_4.newLine();
    {
      EList<Experience> _experience = cv.getExperience();
      for(final Experience experience : _experience) {
        _builder_4.append("                      ");
        _builder_4.append("<li>");
        String _position = experience.getPosition();
        _builder_4.append(_position, "                      ");
        _builder_4.append(" - ");
        String _company = experience.getCompany();
        _builder_4.append(_company, "                      ");
        _builder_4.append(" (\'");
        int _year_1 = experience.getYear();
        _builder_4.append(_year_1, "                      ");
        _builder_4.append("\')</li>");
        _builder_4.newLineIfNotEmpty();
      }
    }
    _builder_4.append("                    ");
    _builder_4.append("</ul>");
    _builder_4.newLine();
    _builder_4.append("                ");
    _builder_4.append("</section>");
    _builder_4.newLine();
    _builder_4.newLine();
    _builder_4.append("                ");
    _builder_4.append("<footer>");
    _builder_4.newLine();
    _builder_4.append("                    ");
    _builder_4.append("<p>Contactez-moi: ");
    String _plus_8 = (_plus_7 + _builder_4);
    String _contact = cv.getContact();
    String _plus_9 = (_plus_8 + _contact);
    StringConcatenation _builder_5 = new StringConcatenation();
    _builder_5.append("</p>");
    _builder_5.newLine();
    _builder_5.append("                ");
    _builder_5.append("</footer>");
    _builder_5.newLine();
    _builder_5.newLine();
    _builder_5.append("            ");
    _builder_5.append("</body>");
    _builder_5.newLine();
    _builder_5.append("            ");
    _builder_5.append("</html>");
    _builder_5.newLine();
    String _plus_10 = (_plus_9 + _builder_5);
    fsa.generateFile(_plus, _plus_10);
  }
}
